version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
